// libs/helical-svelte/src/sidebar/Provider.svelte
<!-- libs/helical-svelte/src/SidebarProvider.svelte -->
<!-- Source: @ark-ui/svelte/factory + drawer (Ark UI), mirrored from @cloudvoyant/helical-react -->
<script lang="ts">
  import {
    SIDEBAR_WIDTH,
    SIDEBAR_WIDTH_ICON,
    SIDEBAR_KEYBOARD_SHORTCUT,
    sidebarStyles,
    cn,
    type SidebarContextProps,
  } from '@cloudvoyant/helical-ui';
  import { setSidebarContext } from './context.svelte';
  import Row from '../Row.svelte';
  import type { Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';

  type Props = {
    defaultOpen?: boolean;
    open?: boolean;
    onOpenChange?: (open: boolean) => void;
    class?: string;
    children?: Snippet;
  } & HTMLAttributes<HTMLDivElement>;

  let { defaultOpen = true, open: openProp, onOpenChange, class: className = '', style, children, ...rest }: Props = $props();

  let isMobile = $state(false);
  let openMobile = $state(false);
  // svelte-ignore state_referenced_locally
  let _open = $state(defaultOpen);
  const open = $derived(openProp ?? _open);
  const contextState = $derived<SidebarContextProps['state']>(open ? 'expanded' : 'collapsed');

  const setOpen = (value: boolean | ((value: boolean) => boolean)) => {
    const openState = typeof value === 'function' ? value(open) : value;
    if (onOpenChange) {
      onOpenChange(openState);
    } else {
      _open = openState;
    }
    if (typeof document !== 'undefined') {
      document.cookie = `sidebar_state=${openState}; path=/; max-age=604800`;
    }
  };

  const toggleSidebar = () => {
    if (isMobile) {
      openMobile = !openMobile;
    } else {
      setOpen((o) => !o);
    }
  };

  $effect(() => {
    const mql = window.matchMedia('(max-width: 767px)');
    const onChange = () => {
      isMobile = window.innerWidth < 768;
    };
    onChange();
    mql.addEventListener('change', onChange);
    return () => mql.removeEventListener('change', onChange);
  });

  $effect(() => {
    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.key === SIDEBAR_KEYBOARD_SHORTCUT && (event.metaKey || event.ctrlKey)) {
        event.preventDefault();
        toggleSidebar();
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  });

  setSidebarContext({
    get state() {
      return contextState;
    },
    get open() {
      return open;
    },
    setOpen,
    get openMobile() {
      return openMobile;
    },
    setOpenMobile(value: boolean | ((open: boolean) => boolean)) {
      openMobile = typeof value === 'function' ? value(openMobile) : value;
    },
    get isMobile() {
      return isMobile;
    },
    toggleSidebar,
  });
</script>

<Row
  data-slot="sidebar-wrapper"
  class={cn(sidebarStyles.wrapperClass, className)}
  style={`--sidebar-width: ${SIDEBAR_WIDTH}; --sidebar-width-icon: ${SIDEBAR_WIDTH_ICON}; ${style ?? ''}`}
  {...rest}
>
  {@render children?.()}
</Row>

// libs/helical-react/src/sidebar/Provider.tsx
// libs/helical-react/src/sidebar/Provider.tsx
// Source: shadcn/ui sidebar (https://ui.shadcn.com/docs/components/base/sidebar),
//         re-based on Ark UI (drawer, tooltip, asChild factory)
/// <reference lib="dom" />
import * as React from 'react';
import {
  SIDEBAR_WIDTH,
  SIDEBAR_WIDTH_ICON,
  SIDEBAR_KEYBOARD_SHORTCUT,
  sidebarStyles,
  cn,
} from '@cloudvoyant/helical-ui';
import { Row } from '../row';
import { SidebarContext } from './context';

const SIDEBAR_COOKIE_NAME = 'sidebar_state';
const SIDEBAR_COOKIE_MAX_AGE = 60 * 60 * 24 * 7;

function useIsMobile() {
  const [isMobile, setIsMobile] = React.useState(false);
  const [isMobileSet, setIsMobileSet] = React.useState(false);

  React.useEffect(() => {
    const mql = window.matchMedia('(max-width: 767px)');
    const onChange = () => {
      setIsMobile(window.innerWidth < 768);
      setIsMobileSet(true);
    };
    onChange();
    mql.addEventListener('change', onChange);
    return () => mql.removeEventListener('change', onChange);
  }, []);

  return isMobile && isMobileSet;
}

export function Provider({
  defaultOpen = true,
  open: openProp,
  onOpenChange: setOpenProp,
  className,
  style,
  children,
  ...props
}: React.ComponentProps<'div'> & {
  defaultOpen?: boolean;
  open?: boolean;
  onOpenChange?: (open: boolean) => void;
}) {
  const isMobile = useIsMobile();
  const [openMobile, setOpenMobile] = React.useState(false);

  const [_open, _setOpen] = React.useState(defaultOpen);
  const open = openProp ?? _open;
  const setOpen = React.useCallback(
    (value: boolean | ((value: boolean) => boolean)) => {
      const openState = typeof value === 'function' ? value(open) : value;
      if (setOpenProp) {
        setOpenProp(openState);
      } else {
        _setOpen(openState);
      }
      if (typeof document !== 'undefined') {
        document.cookie = `${SIDEBAR_COOKIE_NAME}=${openState}; path=/; max-age=${SIDEBAR_COOKIE_MAX_AGE}`;
      }
    },
    [setOpenProp, open],
  );

  const toggleSidebar = React.useCallback(() => {
    return isMobile ? setOpenMobile((open) => !open) : setOpen((open) => !open);
  }, [isMobile, setOpen, setOpenMobile]);

  React.useEffect(() => {
    if (openProp !== undefined) return;
    if (typeof document === 'undefined') return;
    const cookie = document.cookie.split('; ').find((row) => row.startsWith(`${SIDEBAR_COOKIE_NAME}=`));
    if (cookie) {
      _setOpen(cookie.split('=')[1] === 'true');
    }
  }, [openProp]);

  React.useEffect(() => {
    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.key === SIDEBAR_KEYBOARD_SHORTCUT && (event.metaKey || event.ctrlKey)) {
        event.preventDefault();
        toggleSidebar();
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [toggleSidebar]);

  const state: 'expanded' | 'collapsed' = open ? 'expanded' : 'collapsed';

  const contextValue = React.useMemo(
    () => ({
      state,
      open,
      setOpen,
      isMobile,
      openMobile,
      setOpenMobile,
      toggleSidebar,
    }),
    [state, open, setOpen, isMobile, openMobile, setOpenMobile, toggleSidebar],
  );

  return (
    <SidebarContext.Provider value={contextValue}>
      <Row
        data-slot="sidebar-wrapper"
        style={
          {
            '--sidebar-width': SIDEBAR_WIDTH,
            '--sidebar-width-icon': SIDEBAR_WIDTH_ICON,
            ...style,
          } as React.CSSProperties
        }
        className={cn(sidebarStyles.wrapperClass, className)}
        {...props}
      >
        {children}
      </Row>
    </SidebarContext.Provider>
  );
}
