// libs/vortex-react/src/editor/FontColorPicker.tsx
// libs/vortex-react/src/editor/FontColorPicker.tsx
import { useEffect, useState } from 'react';
import type { Editor } from '@tiptap/react';
import { Palette, Highlighter } from 'lucide-react';
import { Popover, PopoverTrigger, PopoverContent } from '..';
import { cn } from '@cloudvoyant/vortex-ui';

const COLORS = ['yellow', 'orange', 'red', 'fuchsia', 'violet', 'blue', 'cyan', 'green', 'slate'] as const;

const TEXT_PREVIEW: Record<string, string> = {
  yellow: '#f59e0b',
  orange: '#f97316',
  red: '#ef4444',
  fuchsia: '#d946ef',
  violet: '#8b5cf6',
  blue: '#3b82f6',
  cyan: '#06b6d4',
  green: '#10b981',
  slate: '#64748b',
};

const HIGHLIGHT_PREVIEW: Record<string, string> = {
  yellow: '#fef9c3',
  orange: '#ffedd5',
  red: '#fee2e2',
  fuchsia: '#fae8ff',
  violet: '#ede9fe',
  blue: '#dbeafe',
  cyan: '#cffafe',
  green: '#d1fae5',
  slate: '#e2e8f0',
};

export interface FontColorPickerProps {
  editor: Editor;
  mode: 'text' | 'highlight';
}

export function FontColorPicker({ editor, mode }: FontColorPickerProps) {
  const [open, setOpen] = useState(false);
  // The editor instance is stable, so a transaction must explicitly re-render this control for
  // `isActive` and the current swatch to follow the selection.
  const [, setRevision] = useState(0);
  const preview = mode === 'highlight' ? HIGHLIGHT_PREVIEW : TEXT_PREVIEW;
  const active = editor.isActive(mode === 'highlight' ? 'highlight' : 'textStyle');
  const currentColor = editor.getAttributes(mode === 'highlight' ? 'highlight' : 'textStyle').color as
    string | undefined;

  useEffect(() => {
    const refresh = () => setRevision((revision) => revision + 1);
    editor.on('transaction', refresh);
    editor.on('selectionUpdate', refresh);
    return () => {
      editor.off('transaction', refresh);
      editor.off('selectionUpdate', refresh);
    };
  }, [editor]);

  function selectColor(colorId: string) {
    if (mode === 'highlight') {
      // Highlight serializes color into an inline `background-color`, which outranks ordinary
      // utility classes. Supply the actual palette color instead of a CSS keyword such as
      // `yellow`, so the mark visibly matches its selected swatch.
      editor
        .chain()
        .focus()
        .toggleHighlight({ color: preview[colorId] ?? colorId })
        .run();
    } else {
      // @tiptap/extension-color writes an inline `style`, so it needs a real CSS colour —
      // a bare palette id like 'slate' is invalid CSS and silently does nothing.
      editor
        .chain()
        .focus()
        .setColor(preview[colorId] ?? colorId)
        .run();
    }
    setOpen(false);
  }

  function clearColor() {
    if (mode === 'highlight') {
      editor.chain().focus().unsetHighlight().run();
    } else {
      editor.chain().focus().unsetColor().run();
    }
    setOpen(false);
  }

  const label = mode === 'highlight' ? 'Highlight color' : 'Text color';

  return (
    <Popover open={open} onOpenChange={(details) => setOpen(details.open)}>
      <PopoverTrigger
        aria-label={label}
        data-state={active ? 'on' : 'off'}
        className={cn(
          'inline-flex h-8 w-8 items-center justify-center rounded-md hover:bg-muted data-[state=on]:bg-accent data-[state=on]:text-accent-foreground',
        )}
      >
        {mode === 'highlight' ? (
          <Highlighter className="h-4 w-4" style={currentColor ? { color: currentColor } : undefined} />
        ) : (
          <Palette className="h-4 w-4" style={currentColor ? { color: currentColor } : undefined} />
        )}
      </PopoverTrigger>
      <PopoverContent className="w-auto p-2">
        <div className="grid grid-cols-5 gap-1">
          {COLORS.map((color) => (
            <button
              key={color}
              type="button"
              aria-label={color}
              onClick={() => selectColor(color)}
              className={cn('h-6 w-6 rounded border border-border transition-transform hover:scale-110')}
              style={{ backgroundColor: preview[color] }}
            />
          ))}
        </div>
        <button type="button" onClick={clearColor} className="mt-2 w-full rounded px-2 py-1 text-xs hover:bg-muted">
          Clear
        </button>
      </PopoverContent>
    </Popover>
  );
}

// libs/vortex-svelte/src/editor/FontColorPicker.svelte
<!-- libs/vortex-svelte/src/editor/FontColorPicker.svelte -->
<script lang="ts">
  import type { Editor } from '@tiptap/core';

  let {
    editor,
    visible = $bindable(false),
    mode = 'color',
  }: {
    editor: Editor;
    visible?: boolean;
    mode?: 'color' | 'highlight';
  } = $props();

  // Reading-friendly color palette with preview colors
  const textColors = [
    { id: 'red', preview: '#dc2626', name: 'Red' },
    { id: 'orange', preview: '#ea580c', name: 'Orange' },
    { id: 'yellow', preview: '#ca8a04', name: 'Yellow' },
    { id: 'green', preview: '#16a34a', name: 'Green' },
    { id: 'cyan', preview: '#0891b2', name: 'Cyan' },
    { id: 'blue', preview: '#2563eb', name: 'Blue' },
    { id: 'violet', preview: '#7c3aed', name: 'Violet' },
    { id: 'fuchsia', preview: '#c026d3', name: 'Fuchsia' },
    { id: 'slate', preview: '#64748b', name: 'Slate' },
  ];

  const highlightColors = [
    { id: 'yellow', preview: '#fef9c3', name: 'Yellow' },
    { id: 'blue', preview: '#dbeafe', name: 'Blue' },
    { id: 'green', preview: '#d1fae5', name: 'Green' },
    { id: 'red', preview: '#fee2e2', name: 'Red' },
    { id: 'fuchsia', preview: '#fae8ff', name: 'Fuchsia' },
    { id: 'orange', preview: '#ffedd5', name: 'Orange' },
    { id: 'violet', preview: '#ede9fe', name: 'Violet' },
    { id: 'cyan', preview: '#cffafe', name: 'Cyan' },
    { id: 'slate', preview: '#f1f5f9', name: 'Slate' },
  ];

  function selectColor(colorId: string) {
    if (mode === 'highlight') {
      // Highlight serializes this as an inline `background-color`, so use the actual preview
      // color rather than a bare CSS keyword such as `yellow`.
      const entry = highlightColors.find((color) => color.id === colorId);
      editor.chain().focus().toggleHighlight({ color: entry?.preview ?? colorId }).run();
    } else {
      // @tiptap/extension-color writes an inline `style`, so it needs a real CSS colour.
      // Passing the palette id ('slate') produces invalid CSS and silently does nothing.
      const entry = textColors.find((c) => c.id === colorId);
      editor
        .chain()
        .focus()
        .setColor(entry?.preview ?? colorId)
        .run();
    }
    visible = false;
  }

  function clearColor() {
    if (mode === 'highlight') {
      editor.chain().focus().unsetHighlight().run();
    } else {
      editor.chain().focus().unsetColor().run();
    }
    visible = false;
  }
</script>

{#if visible}
  <div class="absolute z-50 mt-2 w-48 rounded-lg border bg-background text-foreground p-1 shadow-lg">
    <div class="text-xs font-medium text-muted-foreground px-3 py-2">
      {mode === 'highlight' ? 'Highlight' : 'Color'}
    </div>
    <div class="flex flex-col">
      <!-- None/Clear option -->
      <button
        type="button"
        class="flex items-center gap-2 rounded px-3 py-1.5 text-sm hover:bg-accent hover:text-accent-foreground transition-colors text-left"
        onclick={clearColor}
      >
        <div class="h-5 w-5 rounded border border-border flex-shrink-0 flex items-center justify-center">
          <span class="text-xs text-muted-foreground">×</span>
        </div>
        <span>None</span>
      </button>
      <!-- Color options -->
      {#each mode === 'highlight' ? highlightColors : textColors as color}
        <button
          type="button"
          class="flex items-center gap-2 rounded px-3 py-1.5 text-sm hover:bg-accent hover:text-accent-foreground transition-colors text-left"
          onclick={() => selectColor(color.id)}
        >
          <div
            class="h-5 w-5 rounded border border-border flex-shrink-0"
            style="background-color: {color.preview}"
          ></div>
          <span>{color.name}</span>
        </button>
      {/each}
    </div>
  </div>
{/if}
